#!/usr/bin/env node
// Emits the vendored WeaponNames.json from the MHGU save editor's weapon data.
//
//   node tools/build-weapons.js "../mhgu-editor"
//
// Like QuestData.json, the result is committed here and regenerated by hand — the editor
// is a separate repo and this app only needs the names, not the ~15 MB of stats behind
// them. Output shape: { "Great Sword": ["Abyssal Gale", ...], ..., "Prowler": [...] }.
//
// Names come from the per-type tree files rather than the editor's weapons.json, which
// only lists one entry per weapon id — the tree files include every upgrade level, and
// those are the names people actually write down ("Dual Scissors", "Ham of Hams" and
// "Sage Lance" are all absent from weapons.json).
const fs = require("fs");
const path = require("path");

const EDITOR = process.argv[2] || path.join(__dirname, "..", "..", "mhgu-editor");
const OUT = path.join(__dirname, "..", "WeaponNames.json");

// App weapon-type label -> the editor's asset filename.
const FILES = {
  "Great Sword": "greatsword", "Long Sword": "longsword", "Sword & Shield": "swordandshield",
  "Dual Blades": "dualblades", "Hammer": "hammer", "Hunting Horn": "huntinghorn",
  "Lance": "lance", "Gunlance": "gunlance", "Switch Axe": "switchaxe",
  "Charge Blade": "chargeblade", "Insect Glaive": "insectglaive",
  "Light Bowgun": "lightbowgun", "Heavy Bowgun": "heavybowgun", "Bow": "bow",
};

const assets = path.join(EDITOR, "src", "assets");
if (!fs.existsSync(assets)) {
  console.error(`Can't find the editor's assets at ${assets}`);
  console.error('usage: node tools/build-weapons.js "path/to/mhgu-editor"');
  process.exit(1);
}

const out = {};
for (const [type, file] of Object.entries(FILES)) {
  const j = JSON.parse(fs.readFileSync(path.join(assets, file + ".json"), "utf8"));
  const names = new Set();
  for (const tree of j.trees || []) for (const lv of tree.levels || []) if (lv.name) names.add(lv.name);
  out[type] = [...names].sort((a, b) => a.localeCompare(b));
}

// Palico weapon names are taken exactly as the editor has them, "F " prefix included —
// that is what the game data says, and guessing at a display form would be inventing it.
const palico = JSON.parse(fs.readFileSync(path.join(assets, "palico_weapons.json"), "utf8"));
out["Prowler"] = [...new Set(Object.values(palico).filter(Boolean))].sort((a, b) => a.localeCompare(b));

fs.writeFileSync(OUT, JSON.stringify(out, null, 1));

const total = Object.values(out).reduce((n, a) => n + a.length, 0);
for (const [t, a] of Object.entries(out)) console.log(`  ${t.padEnd(16)} ${a.length}`);
console.log(`Wrote WeaponNames.json — ${total} names across ${Object.keys(out).length} types (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
