#!/usr/bin/env node
// Emits docs/data.js from the vendored QuestData.json + LgMonsters.json.
//
// Those two files are copies of the MHGU Quest Randomizer's canonical data. When they
// change over there, re-copy them here and re-run this script — there is no automatic
// sync, deliberately (see CLAUDE.md).
//
//   node tools/build-data.js
//
// Output is a single `window.MHGU_LOG_DATA = {...}` assignment, matching the
// randomizer's data.js convention so the browser needs no module loader.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const QUEST_SRC = path.join(ROOT, "QuestData.json");
const MONSTER_SRC = path.join(ROOT, "LgMonsters.json");
const WEAPON_SRC = path.join(ROOT, "WeaponNames.json");
const OUT = path.join(ROOT, "docs", "data.js");

// Every quest field the log actually reads. Hunter Arts are dropped entirely (this app
// rolls nothing), as are the Arena-only ArenaWeapons/ArenaBiases arrays — the weapon on a
// log entry is whatever the hunter actually brought, typed in by hand.
const QUEST_FIELDS = [
  "Type", "Name", "Main", "Monster", "Monsters", "Level", "Locale",
  "LgMonster", "Prowler", "Hyper", "Egg", "Gathering", "SmMonsters",
  "Capture", "OnSite", "OneFaint", "Key",
];

function read(file) {
  const parsed = JSON.parse(fs.readFileSync(file, "utf8"));
  if (!Array.isArray(parsed)) throw new Error(`${path.basename(file)} is not a JSON array`);
  return parsed;
}

function trimQuest(q) {
  const out = {};
  for (const key of QUEST_FIELDS) {
    if (key === "Monsters") out.Monsters = Array.isArray(q.Monsters) ? q.Monsters : [];
    else if (key === "Level") out.Level = q.Level | 0;
    else if (typeof q[key] === "boolean") out[key] = q[key];
    else out[key] = q[key] == null ? "" : q[key];
  }
  return out;
}

const monsters = read(MONSTER_SRC).map(m => ({ MonsterName: m.MonsterName, Species: m.Species }));

// Saved log entries key on Type + "//" + Name, so that has to be unique. Upstream
// QuestData.json currently repeats five Village quests as byte-identical rows (a data
// bug over in the Randomizer, harmless there beyond double-weighting them in the roll
// pool). Collapse exact repeats; shout about a collision between rows that actually
// differ, because that one can't be resolved automatically and would make a saved entry
// point at the wrong quest after a data refresh.
const quests = [];
const byKey = new Map();
for (const q of read(QUEST_SRC).map(trimQuest)) {
  const key = q.Type + "//" + q.Name;
  const prev = byKey.get(key);
  if (!prev) { byKey.set(key, q); quests.push(q); continue; }
  if (JSON.stringify(prev) !== JSON.stringify(q))
    console.warn(`WARNING: "${key}" appears twice with different data — entries keyed on it are ambiguous.`);
}
const dropped = byKey.size ? read(QUEST_SRC).length - quests.length : 0;
if (dropped) console.log(`Collapsed ${dropped} duplicate quest row(s).`);

// The name of the icon a quest should show is derived, not stored — and for the ~195
// quests with no Monster field it has to be parsed out of the objective text, where the
// monster is usually plural ("Slay 10 Maccao", "Slay 8 Melynxes"). Depluralising blind
// mangles names that are already singular (Rhenoplos → Rhenoplo), so instead the app
// tries each candidate spelling against this list and keeps the one that exists. Emitting
// it at build time is the only way a static page can know what's on disk.
const ICON_DIR = path.join(ROOT, "docs", "assets", "MonsterIcons");
const icons = fs.readdirSync(ICON_DIR)
  .map(f => /^MHGU-(.+)_Icon\.(webp|png)$/.exec(f))
  .filter(Boolean)
  .map(m => m[1].replace(/_/g, " "))
  .sort();

// Weapon names per type, for the entry form's autocomplete. Generated separately by
// tools/build-weapons.js from the save editor's data — see WeaponNames.json.
let weapons = {};
try {
  weapons = JSON.parse(fs.readFileSync(WEAPON_SRC, "utf8"));
} catch (e) {
  console.warn("WARNING: no WeaponNames.json — weapon autocomplete will be empty. Run tools/build-weapons.js.");
}
const weaponCount = Object.values(weapons).reduce((n, a) => n + a.length, 0);

const banner = "// Auto-generated by tools/build-data.js. Do not edit by hand.\n";
fs.writeFileSync(OUT, banner + "window.MHGU_LOG_DATA = " + JSON.stringify({ quests, monsters, icons, weapons }) + ";\n");

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`Wrote docs/data.js — ${quests.length} quests, ${monsters.length} monsters, ${icons.length} icons, ${weaponCount} weapon names (${kb} KB)`);
